version: "3"

services:

  revealjs:
    image: $REVEALJS
    container_name: "${PROJECT_NAME}_revealjs"
    ports:
      # Used for notify changes.
      - "8000:8000"
      - "35729:35729"
    volumes:
      - $PROJECT_DOCROOT/slides:/slides